name: OpenAPI GitHub Pages Documentation
description: Convert OpenAPI specification to API documentation and publish to GitHub Pages
branding:
  icon: 'upload-cloud'
  color: 'white'

# GitHub Action inputs
inputs:
  openapi-json-filepath:
    description: Filepath of OpenAPI JSON spec
    required: true
  api-docs-filepath:
    description: Filepath to use for generated API docs HTML
    required: true

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

runs:
  using: composite
  steps:
    - name: Checkout source package
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - name: Install pre-requisites
      run: |
        sudo npm install -g @redocly/cli
        sudo snap install yq
      shell: bash
    - name: Fetch generate-docs.sh script
      uses: actions/checkout@v4
      with:
        repository: msayson/openapi-github-pages-action
        sparse-checkout: |
          scripts/generate-docs.sh
        sparse-checkout-cone-mode: false
        path: openapi-github-pages-scripts
    - name: Generate ReDoc API documentation
      run: openapi-github-pages-scripts/scripts/generate-docs.sh
      shell: bash
      env:
        OPENAPI_JSON_FILEPATH: ${{ inputs.openapi-json-filepath }}
        API_DOCS_HTML_FILEPATH: ${{ inputs.api-docs-filepath }}
    - name: Set up GitHub Pages
      uses: actions/configure-pages@v5
    - name: Infer API docs directory
      id: get-api-docs-dir
      run: echo "api-docs-dir=$(dirname "${API_DOCS_HTML_FILEPATH}")" >> $GITHUB_OUTPUT
      shell: bash
    - name: Upload API docs to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ steps.get-api-docs-dir.outputs.api-docs-dir }}
    - name: Deploy GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
